# .goreleaser.yml
# Build customization
builds:
  - binary: helmsman
    ldflags: -s -w -X main.build={{.Version}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/helmsman/main.go   
